gil_queazy_accueil:
    path:     /
    defaults: { _controller: GILQueazyBundle:Accueil:accueil }
    
gil_queazy_quiz:
    path:     /
    defaults: { _controller: GILQueazyBundle:Accueil:accueil }
    
gil_queazy_login:
    path:     /
    defaults: { _controller: GILQueazyBundle:Accueil:accueil }
