    # Listage de l'ensemble des quiz
gil_queazy_quiz:
    path:     /quiz
    defaults: { _controller: GILQueazyBundle:Visitor/ListeQuiz:liste }

# Visualisation du quiz
gil_queazy_quiz_questions:
    path:     /quiz/{quiz_id}
    defaults: { _controller: GILQueazyBundle:Visitor/ViewQuiz:view }
    requirements:
      quiz_id: \d+

# Visualisation d'une question d'un quiz en particulier
gil_queazy_quiz_questions_view:
    path:     /quiz/{quiz_id}/question/{question_id}
    defaults: { _controller: GILQueazyBundle:Visitor/ViewQuiz:viewQuestion }
    requirements:
      quiz_id: \d+
      question_id: \d+

# Visualisation du résultat final du quiz
gil_queazy_delete_quiz:
    path:     /quiz/{quiz_id}/resultat
    defaults: { _controller: GILQueazyBundle:Visitor/ViewQuiz:resultat }
    requirements:
          quiz_id: \d+

# Suppression d'un quiz
gil_queazy_delete_quiz:
    path:     /user/{userID}/delete/{quizID}
    defaults: { _controller: GILQueazyBundle:User/DeleteQuiz:delete }
    requirements:
          quiz_id: \d+
          question_id: \d+
# Affichage du panneau administrateur
# - Affichage de l'ensemble des utilisateurs
# - Lien vers les quiz associés à chaque utilisateur
# - IL NE DOIT Y AVOIR QU'UN SEUL ADMINISTRATEUR
gil_queazy_admin:
    path:     /admin
    defaults: { _controller: GILQueazyBundle:Admin/Admin:index }

# Accueil de l'application
gil_queazy_accueil:
    path:     /
    defaults: { _controller: GILQueazyBundle:Visitor/Accueil:accueil }

# Page de l'utilisateur pour gérer ses propres quiz
gil_queazy_user:
    path:     /user/{id}
    defaults: { _controller: GILQueazyBundle:User/User:user }
    requirements:
        id: \d+

gil_queazy_add_quiz:
    path:   /user/{id}/add
    defaults: { _controller: GILQueazyBundle:User/AddQuiz:addQuiz }
    requirements:
        id: \d+

gil_queazy_add_quiz_question:
    path:   /user/{id}/add/{quiz_id}
    defaults: { _controller: GILQueazyBundle:User/AddQuiz:add }
    requirements:
        id: \d+
        quiz_id: \d+

gil_queazy_add_question:
    path:   /user/{id}/add/{quiz_id}/question
    defaults: { _controller: GILQueazyBundle:User/AddQuiz:addAnswer }
    requirements:
        id: \d+
        quiz_id: \d+